version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: supportdesk_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: supportdesk
    ports:
      - "5432:5432"
    volumes:
      - ./backend/scripts/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
      - ./backend/scripts/seed_data.sql:/docker-entrypoint-initdb.d/seed_data.sql

volumes:
  postgres_data:
